name: PSR-12 coding standard, Test, Coverage
on:
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  coding-standard:
    name: PSR-12 coding standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PHP code sniffer
        run: composer global require squizlabs/php_codesniffer

      - name: Check against PSR12 standard
        run: |
          `composer global config bin-dir --absolute --quiet`/phpcs --standard=PSR12 ./src

  tests:
    needs: coding-standard
    name: PHP [${{ matrix.php }}] - Lumen [${{ matrix.lumen }}]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.1, 8.2 ]
        lumen: [ 10 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require laravel/lumen:^${{ matrix.lumen }} --no-interaction --prefer-dist

      - name: Run test suite
        run: ./vendor/bin/phpunit --testdox

  coverage:
    name: Coverage
    if: github.ref != 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: 8.2

      - name: Install dependencies
        run: composer require laravel/lumen:"^9" --no-interaction --prefer-dist

      - name: Run tests for coverage
        run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Push to Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
